# Generated by Django 3.0.6 on 2020-07-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='conclusion',
        ),
        migrations.AddField(
            model_name='blog',
            name='discussion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='overview',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
