# Generated by Django 3.0.6 on 2020-07-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author_image', models.ImageField(default='', upload_to='blog/images')),
                ('bio', models.CharField(max_length=150)),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
            ],
        ),
    ]
