# Generated by Django 3.0.6 on 2020-07-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='para3',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
