# Generated by Django 3.0.6 on 2020-07-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_about_para3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=150)),
            ],
        ),
    ]
