# Generated by Django 3.0.6 on 2020-07-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200712_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='conclusion',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='overview',
        ),
    ]
